
export default function decorate(block) {
    // Extract the title (first cell)
    const titleRow = block.querySelector(':scope > div:first-child');
    if (titleRow) {
      const titleText = titleRow.textContent.trim();
      const heading = document.createElement('h2');
      heading.className = 'sitemap-v1-title';
      heading.textContent = titleText;
      // Replace the raw first div row with the structured heading
      titleRow.replaceWith(heading);
    }
  
    // Create a wrapper for the list columns container
    const columnsContainer = document.createElement('div');
    columnsContainer.className = 'sitemap-v1-columns';
  
    // Process the remaining rows/columns containing the lists
    const contentRows = block.querySelectorAll(':scope > div');
    contentRows.forEach((row) => {
      // Find all table-cell divs generated by the document table
      const cells = row.querySelectorAll(':scope > div');
      cells.forEach((cell) => {
        cell.className = 'sitemap-v1-column';
        
        // Clean up any inner list stylings if needed
        const uls = cell.querySelectorAll('ul');
        uls.forEach((ul) => {
          ul.className = 'sitemap-v1-list';
        });
  
        columnsContainer.appendChild(cell);
      });
      // Remove the original row container wrapper
      row.remove();
    });
  
    block.appendChild(columnsContainer);
  }